export const TEMPLATE_TYPE = {
  GENERAL: 'GENERAL',
  REAL_ESTATE: 'REAL_ESTATE',
  RETOUCHING: 'RETOUCHING',
  PRODUCT: 'PRODUCT',
  NEW_BORN: 'NEW_BORN',
};

export const DATA_TYPE = {
  BASIC: 'BASIC',
  ADVANCE: 'ADVANCE',
  ADDON: 'ADDON',
  RETOUCHING: 'RETOUCHING',
  FORM: 'FORM',
};
